name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'module/**'
      - 'update.json'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new release?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      mark_prerelease:
        description: "Mark as prerelease?"
        required: true
        type: boolean
        default: false
      mark_draft:
        description: "Mark release as draft?"
        required: true
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set variables
        id: setup
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f2)
          COMMIT_ID=$(git rev-parse --short HEAD)
          VERSION=$(jq -r .version update.json)
          CHANGELOG=CHANGELOG.md
          ZIP_NAME=$REPO_NAME-$COMMIT_ID
          RELEASE_ZIP=$REPO_NAME
          MODULE_PATH="$(pwd)/module/"
          
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "CHANGELOG=${CHANGELOG}" >> $GITHUB_ENV
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
          echo "RELEASE_ZIP=${RELEASE_ZIP}" >> $GITHUB_ENV
          echo "MODULE_PATH=$MODULE_PATH" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.MODULE_PATH }}**

      - name: Compressing files
        if: ${{ inputs.create_release == 'true' }}
        run: |
          echo "Compressing files..."
          cd ${{ env.MODULE_PATH }}
          zip -r ${{ env.RELEASE_ZIP }}.zip *
          echo "Created zip file: ${{ env.RELEASE_ZIP }}.zip"
          mv *.zip ../
          echo "Moved file down a dir"

      - name: Create release
        if: ${{ inputs.create_release == 'true' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "${{ env.RELEASE_ZIP }}.zip"
          tag_name: "${{ env.VERSION }}"
          name: "Release ${{ env.VERSION }}"
          body_path: "${{ env.CHANGELOG }}"
          draft: ${{ inputs.mark_draft }}
          prerelease: ${{ inputs.mark_prerelease }}